import type { FishDef } from '../../types'

// 渤海海域鱼类 (1-25)
export const BOHAI_FISH: FishDef[] = [
  {
    id: 'fish_001',
    name: '梭鱼',
    scientificName: 'Planiliza haematocheila',
    family: '鲻科',
    habit: '沙泥底质',
    distribution: '中国黄海沿海',
    minW: 1.3,
    maxW: 8.7,
    rarity: 1 as Rarity,
    value: 35,
    valueMax: 82,
    bait: ['bait_005'],
    fight: 'gentle',
    desc: '梭鱼，学名Planiliza haematocheila，鲻科。普通级鱼种。',
    dayActive: false,
    nightActive: false,
    depthMin: 4,
    depthMax: 19,
  },
  {
    id: 'fish_002',
    name: '海鲶鱼',
    scientificName: 'Arius sinensis',
    family: '海鲶科',
    habit: '远海洄游',
    distribution: '中国黄海沿海',
    minW: 1.2,
    maxW: 4.8,
    rarity: 1 as Rarity,
    value: 33,
    valueMax: 48,
    bait: ['bait_005'],
    fight: 'gentle',
    desc: '海鲶鱼，学名Arius sinensis，海鲶科。普通级鱼种。',
    dayActive: true,
    nightActive: false,
    depthMin: 2,
    depthMax: 37,
  },
  {
    id: 'fish_003',
    name: '虾虎鱼',
    scientificName: 'Rhinogobius spp.',
    family: '虾虎鱼科',
    habit: '沙泥底质',
    distribution: '中国东海沿海',
    minW: 1.5,
    maxW: 7.1,
    rarity: 1 as Rarity,
    value: 26,
    valueMax: 59,
    bait: ['bait_002'],
    fight: 'gentle',
    desc: '虾虎鱼，学名Rhinogobius spp.，虾虎鱼科。普通级鱼种。',
    dayActive: false,
    nightActive: true,
    depthMin: 3,
    depthMax: 64,
  },
  {
    id: 'fish_004',
    name: '斑尾复虾虎鱼',
    scientificName: 'Synechogobius ommaturus',
    family: '虾虎鱼科',
    habit: '珊瑚礁区',
    distribution: '中国黄海沿海',
    minW: 0.8,
    maxW: 9.8,
    rarity: 1 as Rarity,
    value: 22,
    valueMax: 36,
    bait: ['bait_001'],
    fight: 'jump',
    desc: '斑尾复虾虎鱼，学名Synechogobius ommaturus，虾虎鱼科。普通级鱼种。',
    dayActive: true,
    nightActive: true,
    depthMin: 2,
    depthMax: 45,
  },
  {
    id: 'fish_005',
    name: '中国对虾',
    scientificName: 'Penaeus chinensis',
    family: '对虾科',
    habit: '中上层鱼类',
    distribution: '中国黄海沿海',
    minW: 2.1,
    maxW: 12.3,
    rarity: 2 as Rarity,
    value: 40,
    valueMax: 52,
    bait: ['bait_001'],
    fight: 'gentle',
    desc: '中国对虾，学名Penaeus chinensis，对虾科。稀有级鱼种。',
    dayActive: true,
    nightActive: true,
    depthMin: 3,
    depthMax: 63,
  },
  {
    id: 'fish_006',
    name: '鲈鱼（河口型）',
    scientificName: 'Lateolabrax japonicus',
    family: '鮨科',
    habit: '底栖生活',
    distribution: '中国南海沿海',
    minW: 1.8,
    maxW: 8.6,
    rarity: 2 as Rarity,
    value: 40,
    valueMax: 73,
    bait: ['bait_002'],
    fight: 'jump',
    desc: '鲈鱼（河口型），学名Lateolabrax japonicus，鮨科。稀有级鱼种。',
    dayActive: true,
    nightActive: true,
    depthMin: 1,
    depthMax: 69,
  },
  {
    id: 'fish_007',
    name: '牙鲆（浅水）',
    scientificName: 'Paralichthys olivaceus',
    family: '牙鲆科',
    habit: '远海洄游',
    distribution: '中国渤海沿海',
    minW: 2.2,
    maxW: 12.5,
    rarity: 2 as Rarity,
    value: 44,
    valueMax: 97,
    bait: ['bait_001'],
    fight: 'jump',
    desc: '牙鲆（浅水），学名Paralichthys olivaceus，牙鲆科。稀有级鱼种。',
    dayActive: true,
    nightActive: true,
    depthMin: 5,
    depthMax: 21,
  },
  {
    id: 'fish_008',
    name: '舌鳎',
    scientificName: 'Cynoglossus robustus',
    family: '舌鳎科',
    habit: '礁石区活动',
    distribution: '中国渤海沿海',
    minW: 1.4,
    maxW: 21.9,
    rarity: 2 as Rarity,
    value: 44,
    valueMax: 99,
    bait: ['bait_005'],
    fight: 'burst',
    desc: '舌鳎，学名Cynoglossus robustus，舌鳎科。稀有级鱼种。',
    dayActive: true,
    nightActive: true,
    depthMin: 10,
    depthMax: 72,
  },
  {
    id: 'fish_009',
    name: '日本鳗鲡',
    scientificName: 'Anguilla japonica',
    family: '鳗鲡科',
    habit: '近海栖息',
    distribution: '中国南海沿海',
    minW: 3.6,
    maxW: 16.1,
    rarity: 3 as Rarity,
    value: 54,
    valueMax: 93,
    bait: ['bait_005'],
    fight: 'burst',
    desc: '日本鳗鲡，学名Anguilla japonica，鳗鲡科。传说级鱼种。',
    dayActive: true,
    nightActive: true,
    depthMin: 11,
    depthMax: 47,
  },
  {
    id: 'fish_010',
    name: '大鲶鱼',
    scientificName: 'Silurus asotus',
    family: '鲶科',
    habit: '底栖生活',
    distribution: '中国东海沿海',
    minW: 4.1,
    maxW: 23.0,
    rarity: 3 as Rarity,
    value: 56,
    valueMax: 104,
    bait: ['bait_005'],
    fight: 'jump',
    desc: '大鲶鱼，学名Silurus asotus，鲶科。传说级鱼种。',
    dayActive: true,
    nightActive: true,
    depthMin: 1,
    depthMax: 32,
  },
  {
    id: 'fish_011',
    name: '黑鮶鱼',
    scientificName: 'Sebastes schlegelii',
    family: '平鲉科',
    habit: '远海洄游',
    distribution: '中国黄海沿海',
    minW: 0.9,
    maxW: 6.5,
    rarity: 1 as Rarity,
    value: 35,
    valueMax: 68,
    bait: ['bait_005'],
    fight: 'jump',
    desc: '黑鮶鱼，学名Sebastes schlegelii，平鲉科。普通级鱼种。',
    dayActive: true,
    nightActive: true,
    depthMin: 11,
    depthMax: 79,
  },
  {
    id: 'fish_012',
    name: '六线鱼',
    scientificName: 'Hexagrammos otakii',
    family: '六线鱼科',
    habit: '珊瑚礁区',
    distribution: '中国渤海沿海',
    minW: 1.1,
    maxW: 10.6,
    rarity: 1 as Rarity,
    value: 28,
    valueMax: 65,
    bait: ['bait_007'],
    fight: 'gentle',
    desc: '六线鱼，学名Hexagrammos otakii，六线鱼科。普通级鱼种。',
    dayActive: true,
    nightActive: true,
    depthMin: 3,
    depthMax: 39,
  },
  {
    id: 'fish_013',
    name: '大泷六线鱼',
    scientificName: 'Hexagrammos otakii',
    family: '六线鱼科',
    habit: '河口咸淡水',
    distribution: '中国东海沿海',
    minW: 1.3,
    maxW: 6.7,
    rarity: 1 as Rarity,
    value: 22,
    valueMax: 59,
    bait: ['bait_007'],
    fight: 'jump',
    desc: '大泷六线鱼，学名Hexagrammos otakii，六线鱼科。普通级鱼种。',
    dayActive: true,
    nightActive: true,
    depthMin: 12,
    depthMax: 36,
  },
  {
    id: 'fish_014',
    name: '许氏平鲉',
    scientificName: 'Sebastes schlegelii',
    family: '平鲉科',
    habit: '远海洄游',
    distribution: '中国东海沿海',
    minW: 0.7,
    maxW: 4.9,
    rarity: 1 as Rarity,
    value: 32,
    valueMax: 60,
    bait: ['bait_007'],
    fight: 'gentle',
    desc: '许氏平鲉，学名Sebastes schlegelii，平鲉科。普通级鱼种。',
    dayActive: false,
    nightActive: false,
    depthMin: 2,
    depthMax: 44,
  },
  {
    id: 'fish_015',
    name: '褐菖鲉',
    scientificName: 'Sebastiscus marmoratus',
    family: '平鲉科',
    habit: '礁石区活动',
    distribution: '中国南海沿海',
    minW: 1.5,
    maxW: 5.5,
    rarity: 1 as Rarity,
    value: 24,
    valueMax: 55,
    bait: ['bait_002'],
    fight: 'gentle',
    desc: '褐菖鲉，学名Sebastiscus marmoratus，平鲉科。普通级鱼种。',
    dayActive: false,
    nightActive: true,
    depthMin: 8,
    depthMax: 57,
  },
  {
    id: 'fish_016',
    name: '牙鲆（深水）',
    scientificName: 'Paralichthys olivaceus',
    family: '牙鲆科',
    habit: '沙泥底质',
    distribution: '中国南海沿海',
    minW: 1.8,
    maxW: 16.3,
    rarity: 2 as Rarity,
    value: 37,
    valueMax: 59,
    bait: ['bait_002'],
    fight: 'burst',
    desc: '牙鲆（深水），学名Paralichthys olivaceus，牙鲆科。稀有级鱼种。',
    dayActive: true,
    nightActive: true,
    depthMin: 3,
    depthMax: 26,
  },
  {
    id: 'fish_017',
    name: '鲈鱼（礁石型）',
    scientificName: 'Lateolabrax japonicus',
    family: '鮨科',
    habit: '河口咸淡水',
    distribution: '中国东海沿海',
    minW: 1.4,
    maxW: 9.1,
    rarity: 2 as Rarity,
    value: 46,
    valueMax: 73,
    bait: ['bait_005'],
    fight: 'gentle',
    desc: '鲈鱼（礁石型），学名Lateolabrax japonicus，鮨科。稀有级鱼种。',
    dayActive: true,
    nightActive: true,
    depthMin: 3,
    depthMax: 34,
  },
  {
    id: 'fish_018',
    name: '真鲷',
    scientificName: 'Pagrus major',
    family: '鲷科',
    habit: '远海洄游',
    distribution: '中国黄海沿海',
    minW: 2.2,
    maxW: 18.4,
    rarity: 2 as Rarity,
    value: 49,
    valueMax: 97,
    bait: ['bait_005'],
    fight: 'jump',
    desc: '真鲷，学名Pagrus major，鲷科。稀有级鱼种。',
    dayActive: true,
    nightActive: true,
    depthMin: 4,
    depthMax: 66,
  },
  {
    id: 'fish_019',
    name: '黄条鰤',
    scientificName: 'Seriola aureovittata',
    family: '鰤科',
    habit: '底栖生活',
    distribution: '中国渤海沿海',
    minW: 4.5,
    maxW: 18.5,
    rarity: 3 as Rarity,
    value: 60,
    valueMax: 76,
    bait: ['bait_001'],
    fight: 'burst',
    desc: '黄条鰤，学名Seriola aureovittata，鰤科。传说级鱼种。',
    dayActive: false,
    nightActive: false,
    depthMin: 6,
    depthMax: 33,
  },
  {
    id: 'fish_020',
    name: '鳕鱼',
    scientificName: 'Gadus macrocephalus',
    family: '鳕科',
    habit: '珊瑚礁区',
    distribution: '中国南海沿海',
    minW: 3.0,
    maxW: 27.5,
    rarity: 3 as Rarity,
    value: 51,
    valueMax: 70,
    bait: ['bait_007'],
    fight: 'gentle',
    desc: '鳕鱼，学名Gadus macrocephalus，鳕科。传说级鱼种。',
    dayActive: true,
    nightActive: true,
    depthMin: 2,
    depthMax: 64,
  },
  {
    id: 'fish_021',
    name: '太平洋鳕鱼王',
    scientificName: 'Gadus macrocephalus',
    family: '鳕科',
    habit: '近海栖息',
    distribution: '中国东海沿海',
    minW: 3.9,
    maxW: 14.0,
    rarity: 3 as Rarity,
    value: 47,
    valueMax: 57,
    bait: ['bait_005'],
    fight: 'sprint',
    desc: '太平洋鳕鱼王，学名Gadus macrocephalus，鳕科。传说级鱼种。',
    dayActive: true,
    nightActive: true,
    depthMin: 4,
    depthMax: 16,
  },
  {
    id: 'fish_022',
    name: '黑鲷',
    scientificName: 'Acanthopagrus schlegelii',
    family: '鲷科',
    habit: '礁石区活动',
    distribution: '中国南海沿海',
    minW: 1.2,
    maxW: 10.0,
    rarity: 1 as Rarity,
    value: 33,
    valueMax: 84,
    bait: ['bait_001'],
    fight: 'gentle',
    desc: '黑鲷，学名Acanthopagrus schlegelii，鲷科。普通级鱼种。',
    dayActive: false,
    nightActive: true,
    depthMin: 2,
    depthMax: 63,
  },
  {
    id: 'fish_023',
    name: '鲈鱼（深水型）',
    scientificName: 'Lateolabrax japonicus',
    family: '鮨科',
    habit: '珊瑚礁区',
    distribution: '中国东海沿海',
    minW: 1.6,
    maxW: 11.8,
    rarity: 1 as Rarity,
    value: 26,
    valueMax: 80,
    bait: ['bait_001'],
    fight: 'gentle',
    desc: '鲈鱼（深水型），学名Lateolabrax japonicus，鮨科。普通级鱼种。',
    dayActive: false,
    nightActive: true,
    depthMin: 2,
    depthMax: 46,
  },
  {
    id: 'fish_024',
    name: '大西洋鲭鱼',
    scientificName: 'Scomber scombrus',
    family: '鲭科',
    habit: '礁石区活动',
    distribution: '中国渤海沿海',
    minW: 1.2,
    maxW: 8.8,
    rarity: 1 as Rarity,
    value: 35,
    valueMax: 49,
    bait: ['bait_002'],
    fight: 'jump',
    desc: '大西洋鲭鱼，学名Scomber scombrus，鲭科。普通级鱼种。',
    dayActive: false,
    nightActive: true,
    depthMin: 11,
    depthMax: 60,
  },
  {
    id: 'fish_025',
    name: '蓝点马鲛',
    scientificName: 'Scomberomorus niphonius',
    family: '鲭科',
    habit: '河口咸淡水',
    distribution: '中国黄海沿海',
    minW: 2.7,
    maxW: 16.6,
    rarity: 2 as Rarity,
    value: 35,
    valueMax: 56,
    bait: ['bait_007'],
    fight: 'gentle',
    desc: '蓝点马鲛，学名Scomberomorus niphonius，鲭科。稀有级鱼种。',
    dayActive: false,
    nightActive: true,
    depthMin: 4,
    depthMax: 44,
  }
]