import type { FishDef } from '../../types'

// 东海海域鱼类 (51-75)
export const DONGHAI_FISH: FishDef[] = [
  {
    id: 'fish_051',
    name: '苏眉鱼',
    scientificName: 'Cheilinus undulatus',
    family: '隆头鱼科',
    habit: '河口咸淡水',
    distribution: '中国南海沿海',
    minW: 3.2,
    maxW: 34.9,
    rarity: 3 as Rarity,
    value: 48,
    valueMax: 89,
    bait: ['bait_001'],
    fight: 'sprint',
    desc: '苏眉鱼，学名Cheilinus undulatus，隆头鱼科。传说级鱼种。',
    dayActive: true,
    nightActive: false,
    depthMin: 10,
    depthMax: 21,
  },
  {
    id: 'fish_052',
    name: '青衣',
    scientificName: 'Thalassoma lunare',
    family: '隆头鱼科',
    habit: '远海洄游',
    distribution: '中国黄海沿海',
    minW: 1.8,
    maxW: 10.5,
    rarity: 2 as Rarity,
    value: 49,
    valueMax: 59,
    bait: ['bait_005'],
    fight: 'gentle',
    desc: '青衣，学名Thalassoma lunare，隆头鱼科。稀有级鱼种。',
    dayActive: true,
    nightActive: false,
    depthMin: 7,
    depthMax: 37,
  },
  {
    id: 'fish_053',
    name: '金鲳',
    scientificName: 'Trachinotus ovatus',
    family: '鲳科',
    habit: '近海栖息',
    distribution: '中国南海沿海',
    minW: 1.5,
    maxW: 9.6,
    rarity: 2 as Rarity,
    value: 45,
    valueMax: 96,
    bait: ['bait_007'],
    fight: 'burst',
    desc: '金鲳，学名Trachinotus ovatus，鲳科。稀有级鱼种。',
    dayActive: true,
    nightActive: false,
    depthMin: 7,
    depthMax: 20,
  },
  {
    id: 'fish_054',
    name: '军曹鱼',
    scientificName: 'Rachycentron canadum',
    family: '军曹鱼科',
    habit: '远海洄游',
    distribution: '中国南海沿海',
    minW: 2.3,
    maxW: 11.4,
    rarity: 2 as Rarity,
    value: 44,
    valueMax: 91,
    bait: ['bait_007'],
    fight: 'jump',
    desc: '军曹鱼，学名Rachycentron canadum，军曹鱼科。稀有级鱼种。',
    dayActive: true,
    nightActive: true,
    depthMin: 6,
    depthMax: 65,
  },
  {
    id: 'fish_055',
    name: '沙丁鱼',
    scientificName: 'Sardinops sagax',
    family: '鲱科',
    habit: '珊瑚礁区',
    distribution: '中国南海沿海',
    minW: 1.2,
    maxW: 7.5,
    rarity: 1 as Rarity,
    value: 28,
    valueMax: 88,
    bait: ['bait_001'],
    fight: 'gentle',
    desc: '沙丁鱼，学名Sardinops sagax，鲱科。普通级鱼种。',
    dayActive: true,
    nightActive: false,
    depthMin: 5,
    depthMax: 26,
  },
  {
    id: 'fish_056',
    name: '乌鲳',
    scientificName: 'Formio niger',
    family: '鲳科',
    habit: '底栖生活',
    distribution: '中国南海沿海',
    minW: 0.7,
    maxW: 9.8,
    rarity: 1 as Rarity,
    value: 31,
    valueMax: 83,
    bait: ['bait_002'],
    fight: 'gentle',
    desc: '乌鲳，学名Formio niger，鲳科。普通级鱼种。',
    dayActive: true,
    nightActive: true,
    depthMin: 1,
    depthMax: 90,
  },
  {
    id: 'fish_057',
    name: '赤点石斑鱼',
    scientificName: 'Epinephelus akaara',
    family: '鮨科',
    habit: '远海洄游',
    distribution: '中国渤海沿海',
    minW: 4.1,
    maxW: 23.5,
    rarity: 3 as Rarity,
    value: 59,
    valueMax: 99,
    bait: ['bait_005'],
    fight: 'gentle',
    desc: '赤点石斑鱼，学名Epinephelus akaara，鮨科。传说级鱼种。',
    dayActive: true,
    nightActive: true,
    depthMin: 9,
    depthMax: 36,
  },
  {
    id: 'fish_058',
    name: '中华鲟',
    scientificName: 'Acipenser sinensis',
    family: '鲟科',
    habit: '沙泥底质',
    distribution: '中国渤海沿海',
    minW: 5.0,
    maxW: 20.8,
    rarity: 4 as Rarity,
    value: 66,
    valueMax: 102,
    bait: ['bait_007'],
    fight: 'scream',
    desc: '中华鲟，学名Acipenser sinensis，鲟科。保护级鱼种。',
    dayActive: false,
    nightActive: false,
    depthMin: 9,
    depthMax: 56,
  },
  {
    id: 'fish_059',
    name: '白鲟',
    scientificName: 'Psephurus gladius',
    family: '匙吻鲟科',
    habit: '河口咸淡水',
    distribution: '中国东海沿海',
    minW: 3.2,
    maxW: 28.3,
    rarity: 4 as Rarity,
    value: 61,
    valueMax: 81,
    bait: ['bait_002'],
    fight: 'long_endurance',
    desc: '白鲟，学名Psephurus gladius，匙吻鲟科。保护级鱼种。',
    dayActive: false,
    nightActive: true,
    depthMin: 6,
    depthMax: 27,
  },
  {
    id: 'fish_060',
    name: '海马',
    scientificName: 'Hippocampus spp.',
    family: '海龙科',
    habit: '珊瑚礁区',
    distribution: '中国东海沿海',
    minW: 4.4,
    maxW: 20.5,
    rarity: 4 as Rarity,
    value: 71,
    valueMax: 92,
    bait: ['bait_007'],
    fight: 'spin',
    desc: '海马，学名Hippocampus spp.，海龙科。保护级鱼种。',
    dayActive: false,
    nightActive: true,
    depthMin: 2,
    depthMax: 26,
  },
  {
    id: 'fish_061',
    name: '花鲈',
    scientificName: 'Lateolabrax maculatus',
    family: '鮨科',
    habit: '近海栖息',
    distribution: '中国东海沿海',
    minW: 1.7,
    maxW: 18.0,
    rarity: 2 as Rarity,
    value: 43,
    valueMax: 56,
    bait: ['bait_007'],
    fight: 'gentle',
    desc: '花鲈，学名Lateolabrax maculatus，鮨科。稀有级鱼种。',
    dayActive: true,
    nightActive: true,
    depthMin: 5,
    depthMax: 33,
  },
  {
    id: 'fish_062',
    name: '四指马鲅',
    scientificName: 'Eleutheronema tetradactylum',
    family: '马鲅科',
    habit: '礁石区活动',
    distribution: '中国东海沿海',
    minW: 2.3,
    maxW: 20.0,
    rarity: 2 as Rarity,
    value: 49,
    valueMax: 107,
    bait: ['bait_002'],
    fight: 'burst',
    desc: '四指马鲅，学名Eleutheronema tetradactylum，马鲅科。稀有级鱼种。',
    dayActive: false,
    nightActive: true,
    depthMin: 11,
    depthMax: 15,
  },
  {
    id: 'fish_063',
    name: '多鳞鱚',
    scientificName: 'Sillago sihama',
    family: '鱚科',
    habit: '珊瑚礁区',
    distribution: '中国南海沿海',
    minW: 0.7,
    maxW: 10.3,
    rarity: 1 as Rarity,
    value: 26,
    valueMax: 76,
    bait: ['bait_002'],
    fight: 'gentle',
    desc: '多鳞鱚，学名Sillago sihama，鱚科。普通级鱼种。',
    dayActive: true,
    nightActive: false,
    depthMin: 12,
    depthMax: 70,
  },
  {
    id: 'fish_064',
    name: '花斑蛇鲻',
    scientificName: 'Saurida undosquamis',
    family: '狗母鱼科',
    habit: '礁石区活动',
    distribution: '中国南海沿海',
    minW: 1.5,
    maxW: 8.7,
    rarity: 1 as Rarity,
    value: 24,
    valueMax: 44,
    bait: ['bait_002'],
    fight: 'gentle',
    desc: '花斑蛇鲻，学名Saurida undosquamis，狗母鱼科。普通级鱼种。',
    dayActive: true,
    nightActive: true,
    depthMin: 2,
    depthMax: 80,
  },
  {
    id: 'fish_065',
    name: '日本绯鲤',
    scientificName: 'Upeneus japonicus',
    family: '羊鱼科',
    habit: '底栖生活',
    distribution: '中国渤海沿海',
    minW: 0.9,
    maxW: 4.1,
    rarity: 1 as Rarity,
    value: 23,
    valueMax: 83,
    bait: ['bait_002'],
    fight: 'jump',
    desc: '日本绯鲤，学名Upeneus japonicus，羊鱼科。普通级鱼种。',
    dayActive: false,
    nightActive: true,
    depthMin: 5,
    depthMax: 41,
  },
  {
    id: 'fish_066',
    name: '黄鳍马面鲀',
    scientificName: 'Thamnaconus hypargyreus',
    family: '单角鲀科',
    habit: '河口咸淡水',
    distribution: '中国黄海沿海',
    minW: 0.8,
    maxW: 9.3,
    rarity: 1 as Rarity,
    value: 25,
    valueMax: 82,
    bait: ['bait_005'],
    fight: 'jump',
    desc: '黄鳍马面鲀，学名Thamnaconus hypargyreus，单角鲀科。普通级鱼种。',
    dayActive: true,
    nightActive: true,
    depthMin: 5,
    depthMax: 62,
  },
  {
    id: 'fish_067',
    name: '大眼鲷',
    scientificName: 'Priacanthus tayenus',
    family: '大眼鲷科',
    habit: '河口咸淡水',
    distribution: '中国南海沿海',
    minW: 0.7,
    maxW: 3.9,
    rarity: 1 as Rarity,
    value: 30,
    valueMax: 63,
    bait: ['bait_001'],
    fight: 'gentle',
    desc: '大眼鲷，学名Priacanthus tayenus，大眼鲷科。普通级鱼种。',
    dayActive: true,
    nightActive: false,
    depthMin: 6,
    depthMax: 36,
  },
  {
    id: 'fish_068',
    name: '日本金线鱼',
    scientificName: 'Nemipterus japonicus',
    family: '金线鱼科',
    habit: '珊瑚礁区',
    distribution: '中国渤海沿海',
    minW: 0.9,
    maxW: 6.2,
    rarity: 1 as Rarity,
    value: 24,
    valueMax: 37,
    bait: ['bait_005'],
    fight: 'jump',
    desc: '日本金线鱼，学名Nemipterus japonicus，金线鱼科。普通级鱼种。',
    dayActive: false,
    nightActive: false,
    depthMin: 4,
    depthMax: 75,
  },
  {
    id: 'fish_069',
    name: '斑点鸡笼鲳',
    scientificName: 'Drepane punctata',
    family: '鸡笼鲳科',
    habit: '珊瑚礁区',
    distribution: '中国渤海沿海',
    minW: 0.9,
    maxW: 9.1,
    rarity: 1 as Rarity,
    value: 24,
    valueMax: 49,
    bait: ['bait_002'],
    fight: 'jump',
    desc: '斑点鸡笼鲳，学名Drepane punctata，鸡笼鲳科。普通级鱼种。',
    dayActive: true,
    nightActive: true,
    depthMin: 8,
    depthMax: 62,
  },
  {
    id: 'fish_070',
    name: '断斑石鲈',
    scientificName: 'Pomadasys hasta',
    family: '石鲈科',
    habit: '沙泥底质',
    distribution: '中国渤海沿海',
    minW: 2.8,
    maxW: 20.2,
    rarity: 2 as Rarity,
    value: 40,
    valueMax: 53,
    bait: ['bait_005'],
    fight: 'jump',
    desc: '断斑石鲈，学名Pomadasys hasta，石鲈科。稀有级鱼种。',
    dayActive: true,
    nightActive: false,
    depthMin: 10,
    depthMax: 65,
  },
  {
    id: 'fish_071',
    name: '花身鯻',
    scientificName: 'Terapon jarbua',
    family: '鯻科',
    habit: '河口咸淡水',
    distribution: '中国渤海沿海',
    minW: 1.1,
    maxW: 9.0,
    rarity: 1 as Rarity,
    value: 29,
    valueMax: 73,
    bait: ['bait_002'],
    fight: 'gentle',
    desc: '花身鯻，学名Terapon jarbua，鯻科。普通级鱼种。',
    dayActive: true,
    nightActive: true,
    depthMin: 4,
    depthMax: 15,
  },
  {
    id: 'fish_072',
    name: '银牙鲆',
    scientificName: 'Cynoglossus arel',
    family: '舌鳎科',
    habit: '近海栖息',
    distribution: '中国东海沿海',
    minW: 1.6,
    maxW: 12.5,
    rarity: 2 as Rarity,
    value: 44,
    valueMax: 69,
    bait: ['bait_005'],
    fight: 'burst',
    desc: '银牙鲆，学名Cynoglossus arel，舌鳎科。稀有级鱼种。',
    dayActive: true,
    nightActive: true,
    depthMin: 10,
    depthMax: 85,
  },
  {
    id: 'fish_073',
    name: '褐毛鲿',
    scientificName: 'Megalonibea fusca',
    family: '石首鱼科',
    habit: '底栖生活',
    distribution: '中国南海沿海',
    minW: 4.2,
    maxW: 14.4,
    rarity: 3 as Rarity,
    value: 59,
    valueMax: 118,
    bait: ['bait_002'],
    fight: 'jump',
    desc: '褐毛鲿，学名Megalonibea fusca，石首鱼科。传说级鱼种。',
    dayActive: true,
    nightActive: true,
    depthMin: 2,
    depthMax: 63,
  },
  {
    id: 'fish_074',
    name: '斜带髭鲷',
    scientificName: 'Hapalogenys nitens',
    family: '石鲈科',
    habit: '底栖生活',
    distribution: '中国东海沿海',
    minW: 1.6,
    maxW: 12.2,
    rarity: 2 as Rarity,
    value: 38,
    valueMax: 67,
    bait: ['bait_001'],
    fight: 'burst',
    desc: '斜带髭鲷，学名Hapalogenys nitens，石鲈科。稀有级鱼种。',
    dayActive: false,
    nightActive: false,
    depthMin: 9,
    depthMax: 67,
  },
  {
    id: 'fish_075',
    name: '条石鲷',
    scientificName: 'Oplegnathus fasciatus',
    family: '石鲷科',
    habit: '沙泥底质',
    distribution: '中国南海沿海',
    minW: 1.2,
    maxW: 22.0,
    rarity: 2 as Rarity,
    value: 41,
    valueMax: 89,
    bait: ['bait_001'],
    fight: 'burst',
    desc: '条石鲷，学名Oplegnathus fasciatus，石鲷科。稀有级鱼种。',
    dayActive: true,
    nightActive: true,
    depthMin: 3,
    depthMax: 44,
  }
]