import type { FishDef } from '../../types'

// 黄海海域鱼类 (26-50)
export const HUANGHAI_FISH: FishDef[] = [
  {
    id: 'fish_026',
    name: '美国红鱼',
    scientificName: 'Sciaenops ocellatus',
    family: '石首鱼科',
    habit: '底栖生活',
    distribution: '中国南海沿海',
    minW: 2.0,
    maxW: 23.5,
    rarity: 2 as Rarity,
    value: 36,
    valueMax: 89,
    bait: ['bait_001'],
    fight: 'gentle',
    desc: '美国红鱼，学名Sciaenops ocellatus，石首鱼科。稀有级鱼种。',
    dayActive: true,
    nightActive: true,
    depthMin: 12,
    depthMax: 78,
  },
  {
    id: 'fish_027',
    name: '海蟹（巨大）',
    scientificName: 'Portunus trituberculatus',
    family: '梭子蟹科',
    habit: '近海栖息',
    distribution: '中国黄海沿海',
    minW: 1.2,
    maxW: 12.8,
    rarity: 2 as Rarity,
    value: 43,
    valueMax: 55,
    bait: ['bait_002'],
    fight: 'burst',
    desc: '海蟹（巨大），学名Portunus trituberculatus，梭子蟹科。稀有级鱼种。',
    dayActive: true,
    nightActive: true,
    depthMin: 2,
    depthMax: 23,
  },
  {
    id: 'fish_028',
    name: '牙鲆（深水大型）',
    scientificName: 'Paralichthys olivaceus',
    family: '牙鲆科',
    habit: '底栖生活',
    distribution: '中国南海沿海',
    minW: 1.6,
    maxW: 17.5,
    rarity: 2 as Rarity,
    value: 42,
    valueMax: 101,
    bait: ['bait_002'],
    fight: 'jump',
    desc: '牙鲆（深水大型），学名Paralichthys olivaceus，牙鲆科。稀有级鱼种。',
    dayActive: true,
    nightActive: true,
    depthMin: 6,
    depthMax: 75,
  },
  {
    id: 'fish_029',
    name: '黄姑鱼',
    scientificName: 'Nibea albiflora',
    family: '石首鱼科',
    habit: '中上层鱼类',
    distribution: '中国黄海沿海',
    minW: 2.8,
    maxW: 10.3,
    rarity: 2 as Rarity,
    value: 48,
    valueMax: 106,
    bait: ['bait_001'],
    fight: 'burst',
    desc: '黄姑鱼，学名Nibea albiflora，石首鱼科。稀有级鱼种。',
    dayActive: true,
    nightActive: true,
    depthMin: 4,
    depthMax: 72,
  },
  {
    id: 'fish_030',
    name: '鳕鱼（大西洋）',
    scientificName: 'Gadus morhua',
    family: '鳕科',
    habit: '河口咸淡水',
    distribution: '中国渤海沿海',
    minW: 1.6,
    maxW: 21.8,
    rarity: 3 as Rarity,
    value: 56,
    valueMax: 105,
    bait: ['bait_007'],
    fight: 'jump',
    desc: '鳕鱼（大西洋），学名Gadus morhua，鳕科。传说级鱼种。',
    dayActive: true,
    nightActive: true,
    depthMin: 8,
    depthMax: 20,
  },
  {
    id: 'fish_031',
    name: '巨型章鱼',
    scientificName: 'Enteroctopus dofleini',
    family: '章鱼科',
    habit: '底栖生活',
    distribution: '中国黄海沿海',
    minW: 4.1,
    maxW: 25.6,
    rarity: 3 as Rarity,
    value: 61,
    valueMax: 109,
    bait: ['bait_005'],
    fight: 'jump',
    desc: '巨型章鱼，学名Enteroctopus dofleini，章鱼科。传说级鱼种。',
    dayActive: true,
    nightActive: true,
    depthMin: 7,
    depthMax: 19,
  },
  {
    id: 'fish_032',
    name: '蓝鳍金枪鱼（亚成）',
    scientificName: 'Thunnus thynnus',
    family: '鲭科',
    habit: '中上层鱼类',
    distribution: '中国南海沿海',
    minW: 3.0,
    maxW: 17.5,
    rarity: 3 as Rarity,
    value: 60,
    valueMax: 99,
    bait: ['bait_007'],
    fight: 'jump',
    desc: '蓝鳍金枪鱼（亚成），学名Thunnus thynnus，鲭科。传说级鱼种。',
    dayActive: false,
    nightActive: false,
    depthMin: 1,
    depthMax: 31,
  },
  {
    id: 'fish_033',
    name: '深海石斑',
    scientificName: 'Epinephelus lanceolatus',
    family: '鮨科',
    habit: '近海栖息',
    distribution: '中国渤海沿海',
    minW: 4.2,
    maxW: 22.5,
    rarity: 3 as Rarity,
    value: 60,
    valueMax: 120,
    bait: ['bait_005'],
    fight: 'burst',
    desc: '深海石斑，学名Epinephelus lanceolatus，鮨科。传说级鱼种。',
    dayActive: true,
    nightActive: false,
    depthMin: 10,
    depthMax: 28,
  },
  {
    id: 'fish_034',
    name: '大黄鱼',
    scientificName: 'Larimichthys crocea',
    family: '石首鱼科',
    habit: '近海栖息',
    distribution: '中国南海沿海',
    minW: 3.0,
    maxW: 32.3,
    rarity: 3 as Rarity,
    value: 59,
    valueMax: 98,
    bait: ['bait_007'],
    fight: 'gentle',
    desc: '大黄鱼，学名Larimichthys crocea，石首鱼科。传说级鱼种。',
    dayActive: false,
    nightActive: true,
    depthMin: 7,
    depthMax: 88,
  },
  {
    id: 'fish_035',
    name: '小黄鱼',
    scientificName: 'Larimichthys polyactis',
    family: '石首鱼科',
    habit: '中上层鱼类',
    distribution: '中国东海沿海',
    minW: 2.4,
    maxW: 24.1,
    rarity: 2 as Rarity,
    value: 39,
    valueMax: 65,
    bait: ['bait_007'],
    fight: 'burst',
    desc: '小黄鱼，学名Larimichthys polyactis，石首鱼科。稀有级鱼种。',
    dayActive: true,
    nightActive: true,
    depthMin: 11,
    depthMax: 67,
  },
  {
    id: 'fish_036',
    name: '带鱼',
    scientificName: 'Trichiurus lepturus',
    family: '带鱼科',
    habit: '底栖生活',
    distribution: '中国东海沿海',
    minW: 1.2,
    maxW: 14.2,
    rarity: 2 as Rarity,
    value: 49,
    valueMax: 78,
    bait: ['bait_005'],
    fight: 'burst',
    desc: '带鱼，学名Trichiurus lepturus，带鱼科。稀有级鱼种。',
    dayActive: false,
    nightActive: true,
    depthMin: 5,
    depthMax: 55,
  },
  {
    id: 'fish_037',
    name: '鲐鱼',
    scientificName: 'Scomber japonicus',
    family: '鲭科',
    habit: '珊瑚礁区',
    distribution: '中国东海沿海',
    minW: 1.4,
    maxW: 8.6,
    rarity: 1 as Rarity,
    value: 25,
    valueMax: 35,
    bait: ['bait_002'],
    fight: 'jump',
    desc: '鲐鱼，学名Scomber japonicus，鲭科。普通级鱼种。',
    dayActive: true,
    nightActive: false,
    depthMin: 8,
    depthMax: 63,
  },
  {
    id: 'fish_038',
    name: '鳓鱼',
    scientificName: 'Ilisha elongata',
    family: '鲱科',
    habit: '沙泥底质',
    distribution: '中国渤海沿海',
    minW: 1.7,
    maxW: 15.0,
    rarity: 2 as Rarity,
    value: 46,
    valueMax: 86,
    bait: ['bait_002'],
    fight: 'burst',
    desc: '鳓鱼，学名Ilisha elongata，鲱科。稀有级鱼种。',
    dayActive: true,
    nightActive: true,
    depthMin: 10,
    depthMax: 76,
  },
  {
    id: 'fish_039',
    name: '银鲳',
    scientificName: 'Pampus argenteus',
    family: '鲳科',
    habit: '近海栖息',
    distribution: '中国南海沿海',
    minW: 2.5,
    maxW: 16.6,
    rarity: 2 as Rarity,
    value: 46,
    valueMax: 62,
    bait: ['bait_005'],
    fight: 'jump',
    desc: '银鲳，学名Pampus argenteus，鲳科。稀有级鱼种。',
    dayActive: false,
    nightActive: true,
    depthMin: 8,
    depthMax: 18,
  },
  {
    id: 'fish_040',
    name: '绿鳍马面鲀',
    scientificName: 'Thamnaconus septentrionalis',
    family: '单角鲀科',
    habit: '礁石区活动',
    distribution: '中国渤海沿海',
    minW: 1.0,
    maxW: 6.3,
    rarity: 1 as Rarity,
    value: 28,
    valueMax: 48,
    bait: ['bait_005'],
    fight: 'gentle',
    desc: '绿鳍马面鲀，学名Thamnaconus septentrionalis，单角鲀科。普通级鱼种。',
    dayActive: true,
    nightActive: true,
    depthMin: 2,
    depthMax: 67,
  },
  {
    id: 'fish_041',
    name: '半滑舌鳎',
    scientificName: 'Cynoglossus semilaevis',
    family: '舌鳎科',
    habit: '远海洄游',
    distribution: '中国黄海沿海',
    minW: 1.4,
    maxW: 17.8,
    rarity: 2 as Rarity,
    value: 49,
    valueMax: 63,
    bait: ['bait_005'],
    fight: 'jump',
    desc: '半滑舌鳎，学名Cynoglossus semilaevis，舌鳎科。稀有级鱼种。',
    dayActive: true,
    nightActive: true,
    depthMin: 9,
    depthMax: 42,
  },
  {
    id: 'fish_042',
    name: '海鲈（七星鲈）',
    scientificName: 'Lateolabrax japonicus',
    family: '鮨科',
    habit: '中上层鱼类',
    distribution: '中国南海沿海',
    minW: 2.6,
    maxW: 22.6,
    rarity: 2 as Rarity,
    value: 47,
    valueMax: 92,
    bait: ['bait_007'],
    fight: 'gentle',
    desc: '海鲈（七星鲈），学名Lateolabrax japonicus，鮨科。稀有级鱼种。',
    dayActive: true,
    nightActive: false,
    depthMin: 9,
    depthMax: 74,
  },
  {
    id: 'fish_043',
    name: '日本带鱼',
    scientificName: 'Trichiurus japonicus',
    family: '带鱼科',
    habit: '中上层鱼类',
    distribution: '中国南海沿海',
    minW: 2.3,
    maxW: 8.9,
    rarity: 2 as Rarity,
    value: 43,
    valueMax: 83,
    bait: ['bait_007'],
    fight: 'burst',
    desc: '日本带鱼，学名Trichiurus japonicus，带鱼科。稀有级鱼种。',
    dayActive: true,
    nightActive: false,
    depthMin: 7,
    depthMax: 90,
  },
  {
    id: 'fish_044',
    name: '鮸鱼',
    scientificName: 'Miichthys miiuy',
    family: '石首鱼科',
    habit: '远海洄游',
    distribution: '中国渤海沿海',
    minW: 1.4,
    maxW: 18.4,
    rarity: 2 as Rarity,
    value: 34,
    valueMax: 66,
    bait: ['bait_002'],
    fight: 'gentle',
    desc: '鮸鱼，学名Miichthys miiuy，石首鱼科。稀有级鱼种。',
    dayActive: false,
    nightActive: true,
    depthMin: 10,
    depthMax: 22,
  },
  {
    id: 'fish_045',
    name: '蓝圆鲹',
    scientificName: 'Decapterus maruadsi',
    family: '鲹科',
    habit: '沙泥底质',
    distribution: '中国东海沿海',
    minW: 1.5,
    maxW: 11.2,
    rarity: 1 as Rarity,
    value: 22,
    valueMax: 57,
    bait: ['bait_007'],
    fight: 'gentle',
    desc: '蓝圆鲹，学名Decapterus maruadsi，鲹科。普通级鱼种。',
    dayActive: true,
    nightActive: true,
    depthMin: 7,
    depthMax: 34,
  },
  {
    id: 'fish_046',
    name: '竹荚鱼',
    scientificName: 'Trachurus japonicus',
    family: '鲹科',
    habit: '中上层鱼类',
    distribution: '中国渤海沿海',
    minW: 0.9,
    maxW: 4.8,
    rarity: 1 as Rarity,
    value: 36,
    valueMax: 69,
    bait: ['bait_002'],
    fight: 'gentle',
    desc: '竹荚鱼，学名Trachurus japonicus，鲹科。普通级鱼种。',
    dayActive: true,
    nightActive: false,
    depthMin: 5,
    depthMax: 32,
  },
  {
    id: 'fish_047',
    name: '褐篮子鱼',
    scientificName: 'Siganus fuscescens',
    family: '篮子鱼科',
    habit: '远海洄游',
    distribution: '中国东海沿海',
    minW: 1.0,
    maxW: 9.8,
    rarity: 1 as Rarity,
    value: 31,
    valueMax: 78,
    bait: ['bait_007'],
    fight: 'gentle',
    desc: '褐篮子鱼，学名Siganus fuscescens，篮子鱼科。普通级鱼种。',
    dayActive: true,
    nightActive: true,
    depthMin: 1,
    depthMax: 82,
  },
  {
    id: 'fish_048',
    name: '黄鳍棘鲷',
    scientificName: 'Acanthopagrus latus',
    family: '鲷科',
    habit: '礁石区活动',
    distribution: '中国东海沿海',
    minW: 2.8,
    maxW: 15.6,
    rarity: 2 as Rarity,
    value: 45,
    valueMax: 73,
    bait: ['bait_002'],
    fight: 'burst',
    desc: '黄鳍棘鲷，学名Acanthopagrus latus，鲷科。稀有级鱼种。',
    dayActive: true,
    nightActive: true,
    depthMin: 6,
    depthMax: 69,
  },
  {
    id: 'fish_049',
    name: '横带髭鲷',
    scientificName: 'Hapalogenys mucronatus',
    family: '石鲈科',
    habit: '底栖生活',
    distribution: '中国黄海沿海',
    minW: 1.3,
    maxW: 5.6,
    rarity: 1 as Rarity,
    value: 23,
    valueMax: 67,
    bait: ['bait_005'],
    fight: 'gentle',
    desc: '横带髭鲷，学名Hapalogenys mucronatus，石鲈科。普通级鱼种。',
    dayActive: true,
    nightActive: true,
    depthMin: 2,
    depthMax: 38,
  },
  {
    id: 'fish_050',
    name: '黄唇鱼',
    scientificName: 'Bahaba taipingensis',
    family: '石首鱼科',
    habit: '沙泥底质',
    distribution: '中国渤海沿海',
    minW: 3.5,
    maxW: 27.8,
    rarity: 3 as Rarity,
    value: 56,
    valueMax: 75,
    bait: ['bait_002'],
    fight: 'gentle',
    desc: '黄唇鱼，学名Bahaba taipingensis，石首鱼科。传说级鱼种。',
    dayActive: true,
    nightActive: true,
    depthMin: 5,
    depthMax: 20,
  }
]