import type { FishDef } from '../../types'

// 南海海域鱼类 (76-100)
export const NANHAI_FISH: FishDef[] = [
  {
    id: 'fish_076',
    name: '二长棘鲷',
    scientificName: 'Parargyrops edita',
    family: '鲷科',
    habit: '河口咸淡水',
    distribution: '中国东海沿海',
    minW: 1.7,
    maxW: 20.4,
    rarity: 2 as Rarity,
    value: 46,
    valueMax: 79,
    bait: ['bait_002'],
    fight: 'jump',
    desc: '二长棘鲷，学名Parargyrops edita，鲷科。稀有级鱼种。',
    dayActive: false,
    nightActive: true,
    depthMin: 5,
    depthMax: 21,
  },
  {
    id: 'fish_077',
    name: '黑棘鲷',
    scientificName: 'Acanthopagrus schlegelii',
    family: '鲷科',
    habit: '底栖生活',
    distribution: '中国渤海沿海',
    minW: 1.3,
    maxW: 11.4,
    rarity: 1 as Rarity,
    value: 26,
    valueMax: 59,
    bait: ['bait_005'],
    fight: 'jump',
    desc: '黑棘鲷，学名Acanthopagrus schlegelii，鲷科。普通级鱼种。',
    dayActive: false,
    nightActive: true,
    depthMin: 11,
    depthMax: 69,
  },
  {
    id: 'fish_078',
    name: '平鲷',
    scientificName: 'Rhabdosargus sarba',
    family: '鲷科',
    habit: '远海洄游',
    distribution: '中国黄海沿海',
    minW: 2.3,
    maxW: 13.1,
    rarity: 2 as Rarity,
    value: 45,
    valueMax: 67,
    bait: ['bait_001'],
    fight: 'gentle',
    desc: '平鲷，学名Rhabdosargus sarba，鲷科。稀有级鱼种。',
    dayActive: false,
    nightActive: true,
    depthMin: 7,
    depthMax: 87,
  },
  {
    id: 'fish_079',
    name: '黄斑鲾',
    scientificName: 'Leiognathus bindus',
    family: '鲾科',
    habit: '珊瑚礁区',
    distribution: '中国东海沿海',
    minW: 1.3,
    maxW: 6.1,
    rarity: 1 as Rarity,
    value: 35,
    valueMax: 63,
    bait: ['bait_005'],
    fight: 'gentle',
    desc: '黄斑鲾，学名Leiognathus bindus，鲾科。普通级鱼种。',
    dayActive: true,
    nightActive: false,
    depthMin: 12,
    depthMax: 41,
  },
  {
    id: 'fish_080',
    name: '短吻鲾',
    scientificName: 'Leiognathus brevirostris',
    family: '鲾科',
    habit: '沙泥底质',
    distribution: '中国东海沿海',
    minW: 1.1,
    maxW: 9.3,
    rarity: 1 as Rarity,
    value: 36,
    valueMax: 47,
    bait: ['bait_002'],
    fight: 'jump',
    desc: '短吻鲾，学名Leiognathus brevirostris，鲾科。普通级鱼种。',
    dayActive: true,
    nightActive: false,
    depthMin: 12,
    depthMax: 34,
  },
  {
    id: 'fish_081',
    name: '黄鳍鲷',
    scientificName: 'Sparus latus',
    family: '鲷科',
    habit: '中上层鱼类',
    distribution: '中国黄海沿海',
    minW: 2.0,
    maxW: 21.6,
    rarity: 2 as Rarity,
    value: 49,
    valueMax: 81,
    bait: ['bait_007'],
    fight: 'jump',
    desc: '黄鳍鲷，学名Sparus latus，鲷科。稀有级鱼种。',
    dayActive: false,
    nightActive: true,
    depthMin: 8,
    depthMax: 56,
  },
  {
    id: 'fish_082',
    name: '黑斑绯鲤',
    scientificName: 'Parupeneus indicus',
    family: '羊鱼科',
    habit: '珊瑚礁区',
    distribution: '中国渤海沿海',
    minW: 1.8,
    maxW: 9.3,
    rarity: 2 as Rarity,
    value: 44,
    valueMax: 76,
    bait: ['bait_005'],
    fight: 'burst',
    desc: '黑斑绯鲤，学名Parupeneus indicus，羊鱼科。稀有级鱼种。',
    dayActive: false,
    nightActive: true,
    depthMin: 3,
    depthMax: 68,
  },
  {
    id: 'fish_083',
    name: '双带黄鲈',
    scientificName: 'Diploprion bifasciatum',
    family: '鮨科',
    habit: '远海洄游',
    distribution: '中国南海沿海',
    minW: 2.1,
    maxW: 8.7,
    rarity: 2 as Rarity,
    value: 34,
    valueMax: 67,
    bait: ['bait_002'],
    fight: 'burst',
    desc: '双带黄鲈，学名Diploprion bifasciatum，鮨科。稀有级鱼种。',
    dayActive: true,
    nightActive: true,
    depthMin: 2,
    depthMax: 22,
  },
  {
    id: 'fish_084',
    name: '驼背鲈',
    scientificName: 'Cromileptes altivelis',
    family: '鮨科',
    habit: '远海洄游',
    distribution: '中国南海沿海',
    minW: 2.1,
    maxW: 13.8,
    rarity: 3 as Rarity,
    value: 46,
    valueMax: 66,
    bait: ['bait_005'],
    fight: 'jump',
    desc: '驼背鲈，学名Cromileptes altivelis，鮨科。传说级鱼种。',
    dayActive: true,
    nightActive: true,
    depthMin: 5,
    depthMax: 15,
  },
  {
    id: 'fish_085',
    name: '宝石石斑鱼',
    scientificName: 'Epinephelus areolatus',
    family: '鮨科',
    habit: '沙泥底质',
    distribution: '中国东海沿海',
    minW: 1.2,
    maxW: 14.7,
    rarity: 2 as Rarity,
    value: 42,
    valueMax: 72,
    bait: ['bait_002'],
    fight: 'gentle',
    desc: '宝石石斑鱼，学名Epinephelus areolatus，鮨科。稀有级鱼种。',
    dayActive: true,
    nightActive: false,
    depthMin: 3,
    depthMax: 43,
  },
  {
    id: 'fish_086',
    name: '青石斑鱼',
    scientificName: 'Epinephelus awoara',
    family: '鮨科',
    habit: '中上层鱼类',
    distribution: '中国南海沿海',
    minW: 1.6,
    maxW: 23.1,
    rarity: 2 as Rarity,
    value: 47,
    valueMax: 81,
    bait: ['bait_001'],
    fight: 'burst',
    desc: '青石斑鱼，学名Epinephelus awoara，鮨科。稀有级鱼种。',
    dayActive: true,
    nightActive: false,
    depthMin: 12,
    depthMax: 82,
  },
  {
    id: 'fish_087',
    name: '点带石斑鱼',
    scientificName: 'Epinephelus coioides',
    family: '鮨科',
    habit: '礁石区活动',
    distribution: '中国东海沿海',
    minW: 1.9,
    maxW: 21.0,
    rarity: 2 as Rarity,
    value: 34,
    valueMax: 81,
    bait: ['bait_007'],
    fight: 'gentle',
    desc: '点带石斑鱼，学名Epinephelus coioides，鮨科。稀有级鱼种。',
    dayActive: true,
    nightActive: true,
    depthMin: 9,
    depthMax: 83,
  },
  {
    id: 'fish_088',
    name: '马拉巴石斑鱼',
    scientificName: 'Epinephelus malabaricus',
    family: '鮨科',
    habit: '近海栖息',
    distribution: '中国黄海沿海',
    minW: 2.9,
    maxW: 23.4,
    rarity: 3 as Rarity,
    value: 57,
    valueMax: 82,
    bait: ['bait_002'],
    fight: 'jump',
    desc: '马拉巴石斑鱼，学名Epinephelus malabaricus，鮨科。传说级鱼种。',
    dayActive: false,
    nightActive: true,
    depthMin: 4,
    depthMax: 25,
  },
  {
    id: 'fish_089',
    name: '花点石斑鱼',
    scientificName: 'Epinephelus fuscoguttatus',
    family: '鮨科',
    habit: '珊瑚礁区',
    distribution: '中国南海沿海',
    minW: 4.3,
    maxW: 37.2,
    rarity: 3 as Rarity,
    value: 54,
    valueMax: 100,
    bait: ['bait_005'],
    fight: 'sprint',
    desc: '花点石斑鱼，学名Epinephelus fuscoguttatus，鮨科。传说级鱼种。',
    dayActive: true,
    nightActive: true,
    depthMin: 6,
    depthMax: 55,
  },
  {
    id: 'fish_090',
    name: '巨石斑鱼',
    scientificName: 'Epinephelus tauvina',
    family: '鮨科',
    habit: '近海栖息',
    distribution: '中国渤海沿海',
    minW: 3.1,
    maxW: 15.0,
    rarity: 3 as Rarity,
    value: 55,
    valueMax: 104,
    bait: ['bait_002'],
    fight: 'jump',
    desc: '巨石斑鱼，学名Epinephelus tauvina，鮨科。传说级鱼种。',
    dayActive: true,
    nightActive: true,
    depthMin: 9,
    depthMax: 62,
  },
  {
    id: 'fish_091',
    name: '鞍带石斑鱼',
    scientificName: 'Epinephelus lanceolatus',
    family: '鮨科',
    habit: '礁石区活动',
    distribution: '中国东海沿海',
    minW: 2.2,
    maxW: 23.0,
    rarity: 3 as Rarity,
    value: 46,
    valueMax: 105,
    bait: ['bait_005'],
    fight: 'gentle',
    desc: '鞍带石斑鱼，学名Epinephelus lanceolatus，鮨科。传说级鱼种。',
    dayActive: true,
    nightActive: true,
    depthMin: 7,
    depthMax: 86,
  },
  {
    id: 'fish_092',
    name: '圆颌针鱼',
    scientificName: 'Tylosurus strongylurus',
    family: '颌针鱼科',
    habit: '珊瑚礁区',
    distribution: '中国南海沿海',
    minW: 1.3,
    maxW: 9.5,
    rarity: 1 as Rarity,
    value: 26,
    valueMax: 61,
    bait: ['bait_005'],
    fight: 'jump',
    desc: '圆颌针鱼，学名Tylosurus strongylurus，颌针鱼科。普通级鱼种。',
    dayActive: true,
    nightActive: false,
    depthMin: 10,
    depthMax: 81,
  },
  {
    id: 'fish_093',
    name: '鲻鱼',
    scientificName: 'Mugil cephalus',
    family: '鲻科',
    habit: '远海洄游',
    distribution: '中国南海沿海',
    minW: 0.7,
    maxW: 6.3,
    rarity: 1 as Rarity,
    value: 30,
    valueMax: 46,
    bait: ['bait_001'],
    fight: 'jump',
    desc: '鲻鱼，学名Mugil cephalus，鲻科。普通级鱼种。',
    dayActive: false,
    nightActive: true,
    depthMin: 2,
    depthMax: 47,
  },
  {
    id: 'fish_094',
    name: '大鳞鲻',
    scientificName: 'Mugil macrolepis',
    family: '鲻科',
    habit: '底栖生活',
    distribution: '中国南海沿海',
    minW: 1.0,
    maxW: 9.4,
    rarity: 1 as Rarity,
    value: 27,
    valueMax: 40,
    bait: ['bait_007'],
    fight: 'jump',
    desc: '大鳞鲻，学名Mugil macrolepis，鲻科。普通级鱼种。',
    dayActive: false,
    nightActive: true,
    depthMin: 8,
    depthMax: 26,
  },
  {
    id: 'fish_095',
    name: '前鳞鲻',
    scientificName: 'Mugil ophuyseni',
    family: '鲻科',
    habit: '远海洄游',
    distribution: '中国黄海沿海',
    minW: 1.3,
    maxW: 5.2,
    rarity: 1 as Rarity,
    value: 37,
    valueMax: 64,
    bait: ['bait_002'],
    fight: 'gentle',
    desc: '前鳞鲻，学名Mugil ophuyseni，鲻科。普通级鱼种。',
    dayActive: true,
    nightActive: true,
    depthMin: 3,
    depthMax: 78,
  },
  {
    id: 'fish_096',
    name: '长鳍篮子鱼',
    scientificName: 'Siganus canaliculatus',
    family: '篮子鱼科',
    habit: '沙泥底质',
    distribution: '中国渤海沿海',
    minW: 1.0,
    maxW: 6.5,
    rarity: 1 as Rarity,
    value: 35,
    valueMax: 76,
    bait: ['bait_001'],
    fight: 'jump',
    desc: '长鳍篮子鱼，学名Siganus canaliculatus，篮子鱼科。普通级鱼种。',
    dayActive: false,
    nightActive: false,
    depthMin: 3,
    depthMax: 19,
  },
  {
    id: 'fish_097',
    name: '点篮子鱼',
    scientificName: 'Siganus guttatus',
    family: '篮子鱼科',
    habit: '中上层鱼类',
    distribution: '中国黄海沿海',
    minW: 1.7,
    maxW: 11.7,
    rarity: 2 as Rarity,
    value: 42,
    valueMax: 54,
    bait: ['bait_007'],
    fight: 'burst',
    desc: '点篮子鱼，学名Siganus guttatus，篮子鱼科。稀有级鱼种。',
    dayActive: true,
    nightActive: false,
    depthMin: 3,
    depthMax: 38,
  },
  {
    id: 'fish_098',
    name: '三线矶鲈',
    scientificName: 'Parapristipoma trilineatum',
    family: '石鲈科',
    habit: '近海栖息',
    distribution: '中国黄海沿海',
    minW: 2.8,
    maxW: 23.1,
    rarity: 2 as Rarity,
    value: 48,
    valueMax: 105,
    bait: ['bait_001'],
    fight: 'gentle',
    desc: '三线矶鲈，学名Parapristipoma trilineatum，石鲈科。稀有级鱼种。',
    dayActive: true,
    nightActive: true,
    depthMin: 6,
    depthMax: 65,
  },
  {
    id: 'fish_099',
    name: '日本鲈',
    scientificName: 'Lateolabrax japonicus',
    family: '鮨科',
    habit: '河口咸淡水',
    distribution: '中国东海沿海',
    minW: 1.6,
    maxW: 11.1,
    rarity: 2 as Rarity,
    value: 46,
    valueMax: 96,
    bait: ['bait_005'],
    fight: 'burst',
    desc: '日本鲈，学名Lateolabrax japonicus，鮨科。稀有级鱼种。',
    dayActive: true,
    nightActive: true,
    depthMin: 11,
    depthMax: 39,
  },
  {
    id: 'fish_100',
    name: '朝鲜鲈',
    scientificName: 'Lateolabrax maculatus',
    family: '鮨科',
    habit: '河口咸淡水',
    distribution: '中国东海沿海',
    minW: 2.9,
    maxW: 17.9,
    rarity: 2 as Rarity,
    value: 45,
    valueMax: 86,
    bait: ['bait_001'],
    fight: 'burst',
    desc: '朝鲜鲈，学名Lateolabrax maculatus，鮨科。稀有级鱼种。',
    dayActive: true,
    nightActive: false,
    depthMin: 2,
    depthMax: 30,
  }
]