import type { EquipDef } from '../../types'

export const BAITS: EquipDef[] = [
  // ── 天然饵料 × 16 ──
  {
    id: 'bait_001',
    name: '沙蚕',
    type: 'bait',
    keywords: ['沙蚕', '虫', '海虫'],
    price: 15,
    maxDurability: 1,
    unlockLevel: 1,
    desc: '万能海钓饵料，对多数肉食性鱼类有强烈吸引力。',
  },
  {
    id: 'bait_002',
    name: '活虾',
    type: 'bait',
    keywords: ['活虾', '虾', '甲壳'],
    price: 25,
    maxDurability: 1,
    unlockLevel: 1,
    desc: '鲜活海虾，大鱼最爱，适合钓捕掠食性鱼类。',
  },
  {
    id: 'bait_003',
    name: '小蟹',
    type: 'bait',
    keywords: ['小蟹', '蟹', '甲壳'],
    price: 20,
    maxDurability: 1,
    unlockLevel: 2,
    desc: '碎壳小蟹，底栖鱼类的最爱，适合近海底层钓。',
  },
  {
    id: 'bait_004',
    name: '海蟑螂',
    type: 'bait',
    keywords: ['海蟑螂', '虫', '海虫'],
    price: 10,
    maxDurability: 1,
    unlockLevel: 1,
    desc: '海边礁石常见，矶钓经典饵料。',
  },
  {
    id: 'bait_005',
    name: '虾肉',
    type: 'bait',
    keywords: ['虾肉', '虾', '甲壳'],
    price: 18,
    maxDurability: 1,
    unlockLevel: 2,
    desc: '去壳鲜虾肉，腥味浓郁，广谱诱鱼。',
  },
  {
    id: 'bait_006',
    name: '贝螺肉',
    type: 'bait',
    keywords: ['贝螺肉', '贝', '螺', '软体'],
    price: 12,
    maxDurability: 1,
    unlockLevel: 2,
    desc: '贝类及螺类的鲜肉，适合底钓鲷科鱼类。',
  },
  {
    id: 'bait_007',
    name: '鱼块',
    type: 'bait',
    keywords: ['鱼块', '鱼肉', '鱼'],
    price: 22,
    maxDurability: 1,
    unlockLevel: 3,
    desc: '新鲜鱼肉切块，血肉腥味能吸引大型掠食者。',
  },
  {
    id: 'bait_008',
    name: '动物内脏',
    type: 'bait',
    keywords: ['动物内脏', '内脏', '腥'],
    price: 10,
    maxDurability: 1,
    unlockLevel: 3,
    desc: '鸡鸭猪内脏，来源方便，诱鱼效果好。',
  },
  {
    id: 'bait_009',
    name: '紫菜',
    type: 'bait',
    keywords: ['紫菜', '藻', '海藻', '植物'],
    price: 12,
    maxDurability: 1,
    unlockLevel: 1,
    desc: '天然紫菜，草食性及杂食性鱼类喜食。',
  },
  {
    id: 'bait_010',
    name: '海白菜',
    type: 'bait',
    keywords: ['海白菜', '藻', '海藻', '植物'],
    price: 14,
    maxDurability: 1,
    unlockLevel: 2,
    desc: '石莼科海藻，草食性鱼类的重要食源。',
  },
  {
    id: 'bait_011',
    name: '浒苔',
    type: 'bait',
    keywords: ['浒苔', '藻', '海藻', '植物'],
    price: 10,
    maxDurability: 1,
    unlockLevel: 1,
    desc: '沿海常见绿藻，适合钓草食性鱼类。',
  },
  {
    id: 'bait_012',
    name: '海发丝',
    type: 'bait',
    keywords: ['海发丝', '藻', '海藻', '植物'],
    price: 16,
    maxDurability: 1,
    unlockLevel: 3,
    desc: '细长形海藻，漂流姿态自然，易引鱼上钩。',
  },
  {
    id: 'bait_013',
    name: '裙带菜',
    type: 'bait',
    keywords: ['裙带菜', '藻', '海藻', '植物'],
    price: 18,
    maxDurability: 1,
    unlockLevel: 2,
    desc: '大型褐藻，草食性鱼类的最爱之一。',
  },
  {
    id: 'bait_014',
    name: '礁膜',
    type: 'bait',
    keywords: ['礁膜', '藻', '海藻', '植物'],
    price: 15,
    maxDurability: 1,
    unlockLevel: 4,
    desc: '礁岩表面藻膜，特殊气味吸引部分底栖鱼。',
  },
  {
    id: 'bait_015',
    name: '海藻棉',
    type: 'bait',
    keywords: ['海藻棉', '藻', '海藻', '植物'],
    price: 20,
    maxDurability: 1,
    unlockLevel: 5,
    desc: '海绵状藻体，吸水性强，持久释放诱鱼气味。',
  },
  {
    id: 'bait_016',
    name: '吐司面团',
    type: 'bait',
    keywords: ['吐司面团', '面团', '谷物'],
    price: 8,
    maxDurability: 1,
    unlockLevel: 1,
    desc: '面包揉制面团，基础饵料，杂食性鱼类均会咬钩。',
  },
  // ── 拟饵 × 2 ──
  {
    id: 'bait_017',
    name: '硬饵(米诺)',
    type: 'lure',
    keywords: ['米诺', '硬饵', 'minnow', '拟饵'],
    price: 80,
    maxDurability: 5,
    unlockLevel: 6,
    desc: '硬质仿生小鱼，舌板设计模仿受伤小鱼泳姿。',
  },
  {
    id: 'bait_018',
    name: '软饵(软虫)',
    type: 'lure',
    keywords: ['软虫', '软饵', 'worm', '拟饵'],
    price: 60,
    maxDurability: 5,
    unlockLevel: 5,
    desc: '硅胶软虫，柔软仿真，水中飘动自然诱鱼。',
  },
]
