import type { ChumDef } from '../../types'

export const CHUMS: ChumDef[] = [
  {
    id: 'chum_001',
    name: '南极虾砖',
    type: 'chum',
    fishTargets: [], // 广谱诱鱼，对所有鱼类均有小幅加成
    casts: 5,
    keywords: ['南极虾', '虾', '磷虾'],
    price: 80,
    maxDurability: 1,
    unlockLevel: 1,
    desc: '经典窝料，南极磷虾压制砖块，化水后腥味扩散极快。',
  },
  {
    id: 'chum_002',
    name: '鱼肉块',
    type: 'chum',
    fishTargets: [], // 广谱肉食鱼
    casts: 6,
    keywords: ['鱼肉', '肉块', '腥'],
    price: 100,
    maxDurability: 1,
    unlockLevel: 2,
    desc: '剁碎鱼肉混合沙土制成，持久释放肉腥味。',
  },
  {
    id: 'chum_003',
    name: '贝肉',
    type: 'chum',
    fishTargets: [], // 鲷科鱼类
    casts: 4,
    keywords: ['贝肉', '贝', '软体'],
    price: 90,
    maxDurability: 1,
    unlockLevel: 2,
    desc: '新鲜贝肉捣碎，对鲷科和底栖鱼类效果显著。',
  },
  {
    id: 'chum_004',
    name: '鱿鱼条',
    type: 'chum',
    fishTargets: [], // 掠食性鱼类
    casts: 5,
    keywords: ['鱿鱼', '鱿鱼条', '软体'],
    price: 110,
    maxDurability: 1,
    unlockLevel: 3,
    desc: '切条鱿鱼，柔软韧性强，大型掠食鱼难以抗拒。',
  },
  {
    id: 'chum_005',
    name: '活泥鳅',
    type: 'chum',
    fishTargets: [], // 大型肉食鱼
    casts: 3,
    keywords: ['泥鳅', '活饵'],
    price: 150,
    maxDurability: 1,
    unlockLevel: 4,
    desc: '鲜活泥鳅入水游动，瞬间激发掠食者攻击本能。',
  },
  {
    id: 'chum_006',
    name: '海蜈蚣',
    type: 'chum',
    fishTargets: [], // 底层鱼
    casts: 4,
    keywords: ['海蜈蚣', '虫'],
    price: 120,
    maxDurability: 1,
    unlockLevel: 3,
    desc: '海边沙中采集的海蜈蚣，沙底鱼类趋之若鹜。',
  },
  {
    id: 'chum_007',
    name: '红虫',
    type: 'chum',
    fishTargets: [], // 小型鱼、鲷科
    casts: 5,
    keywords: ['红虫', '虫'],
    price: 60,
    maxDurability: 1,
    unlockLevel: 1,
    desc: '细小红色虫体，腥味浓郁，杂食性鱼类通杀。',
  },
  {
    id: 'chum_008',
    name: '小蟹',
    type: 'chum',
    fishTargets: [], // 底栖、石斑类
    casts: 3,
    keywords: ['小蟹', '蟹', '甲壳'],
    price: 130,
    maxDurability: 1,
    unlockLevel: 4,
    desc: '碎壳小蟹混入泥沙打窝，底部甲壳类食性的鱼会聚集。',
  },
  {
    id: 'chum_009',
    name: '商品粉饵',
    type: 'chum',
    fishTargets: [], // 广谱
    casts: 8,
    keywords: ['粉饵', '商品饵'],
    price: 50,
    maxDurability: 1,
    unlockLevel: 1,
    desc: '工业化调配粉状窝料，雾化快，诱鱼范围广。',
  },
  {
    id: 'chum_010',
    name: '小鸡饲料',
    type: 'chum',
    fishTargets: [], // 杂食鱼
    casts: 10,
    keywords: ['小鸡饲料', '饲料', '谷物'],
    price: 40,
    maxDurability: 1,
    unlockLevel: 1,
    desc: '廉价实用窝料，含谷物颗粒，对杂食性鱼效果不错。',
  },
  {
    id: 'chum_011',
    name: '虾皮',
    type: 'chum',
    fishTargets: [], // 小型鱼
    casts: 6,
    keywords: ['虾皮', '虾', '甲壳'],
    price: 55,
    maxDurability: 1,
    unlockLevel: 2,
    desc: '干虾皮碾碎撒入窝点，缓缓释放虾腥味。',
  },
  {
    id: 'chum_012',
    name: '虾油/鱼露',
    type: 'chum',
    fishTargets: [], // 广谱
    casts: 4,
    keywords: ['虾油', '鱼露', '腥'],
    price: 85,
    maxDurability: 1,
    unlockLevel: 3,
    desc: '高度浓缩虾油鱼露，气味穿透力极强，混沙土使用。',
  },
  {
    id: 'chum_013',
    name: '麦麸/面包屑',
    type: 'chum',
    fishTargets: [], // 杂食鱼、草食鱼
    casts: 8,
    keywords: ['麦麸', '面包屑', '谷物'],
    price: 35,
    maxDurability: 1,
    unlockLevel: 1,
    desc: '轻质谷物窝料，入水飘散，适合表层及中层水域诱鱼。',
  },
  {
    id: 'chum_014',
    name: '鸡肝/鸭肝',
    type: 'chum',
    fishTargets: [], // 肉食性鱼
    casts: 4,
    keywords: ['鸡肝', '鸭肝', '内脏'],
    price: 75,
    maxDurability: 1,
    unlockLevel: 3,
    desc: '家禽肝脏捣碎打窝，血腥味扩散快，肉食鱼闻讯而来。',
  },
  {
    id: 'chum_015',
    name: '秘制混合窝料',
    type: 'chum',
    fishTargets: [], // 稀有/史诗鱼
    casts: 3,
    keywords: ['秘制', '混合', '高级'],
    price: 500,
    maxDurability: 1,
    unlockLevel: 10,
    desc: '多种珍贵材料秘制而成，据传能吸引珍稀鱼种。',
  },
]
