import type { EquipDef } from '../../types'

export const FLOATS: EquipDef[] = [
  {
    id: 'float_001',
    name: '烟海纳米浮漂',
    type: 'float',
    brand: '烟海',
    power: undefined,
    rareBonus: 3,
    maxDurability: 60,
    price: 120,
    unlockLevel: 1,
    desc: '纳米材质浮漂，浮力大且稳定，新手首选。',
  },
  {
    id: 'float_002',
    name: '宫之浦阿波漂',
    type: 'float',
    brand: '宫之浦',
    power: undefined,
    rareBonus: 5,
    maxDurability: 80,
    price: 200,
    unlockLevel: 5,
    desc: '经典阿波浮漂，水下抗流性能出色。',
  },
  {
    id: 'float_003',
    name: '钓研GYRO-N',
    type: 'float',
    brand: '钓研GYRO-N',
    power: undefined,
    rareBonus: 8,
    maxDurability: 100,
    price: 350,
    unlockLevel: 10,
    desc: '旋转式浮漂，减少风线缠绕，远投稳定。',
  },
  {
    id: 'float_004',
    name: '禧玛诺BB-X ZERO PIT',
    type: 'float',
    brand: '禧玛诺BB-X ZERO PIT',
    power: undefined,
    rareBonus: 12,
    maxDurability: 120,
    price: 500,
    unlockLevel: 16,
    desc: '禧玛诺高端浮漂，超远投设计，夜光涂装。',
  },
]
