import type { EquipDef } from '../../types'

export const HOOKS: EquipDef[] = [
  {
    id: 'hook_001',
    name: '矶工坊千又钩',
    type: 'hook',
    brand: '矶工坊',
    power: 3,
    rareBonus: 0,
    maxDurability: 50,
    price: 80,
    unlockLevel: 1,
    desc: '基础千又钩型，适合中小型海鱼。',
  },
  {
    id: 'hook_002',
    name: '哈里米兹管付钩',
    type: 'hook',
    brand: '哈里米兹',
    power: 8,
    rareBonus: 3,
    maxDurability: 80,
    price: 150,
    unlockLevel: 4,
    desc: '管付设计防脱线，适合中大型鱼。',
  },
  {
    id: 'hook_003',
    name: '黑金刚(BKK)三本钩',
    type: 'hook',
    brand: '黑金刚(BKK)',
    power: 15,
    rareBonus: 5,
    maxDurability: 110,
    price: 250,
    unlockLevel: 8,
    desc: '高强度三本钩，路亚锚鱼利器。',
  },
  {
    id: 'hook_004',
    name: '伽玛卡兹丸世巨钩',
    type: 'hook',
    brand: '伽玛卡兹',
    power: 25,
    rareBonus: 8,
    maxDurability: 150,
    price: 400,
    unlockLevel: 14,
    desc: '大型丸世钩，钩条粗壮，专擒深海巨物。',
  },
]
