import type { EquipDef } from '../../types'

export const LINES: EquipDef[] = [
  {
    id: 'line_001',
    name: 'Sunline PE 1.0号',
    type: 'line',
    brand: 'Sunline',
    power: 5,
    rareBonus: 0,
    maxDurability: 80,
    price: 150,
    unlockLevel: 1,
    desc: '入门PE线，八股编织，顺滑出线。',
  },
  {
    id: 'line_002',
    name: '西格碳素线 2.0号',
    type: 'line',
    brand: '西格',
    power: 12,
    rareBonus: 2,
    maxDurability: 100,
    price: 250,
    unlockLevel: 3,
    desc: '高耐磨碳素线，切水性好，隐蔽性佳。',
  },
  {
    id: 'line_003',
    name: 'Varivas 大物线',
    type: 'line',
    brand: 'Varivas',
    power: 20,
    rareBonus: 4,
    maxDurability: 120,
    price: 350,
    unlockLevel: 5,
    desc: '重型PE线，高强度编织，适合大型鱼种。',
  },
  {
    id: 'line_004',
    name: 'YGK 矶钓线 3.0号',
    type: 'line',
    brand: 'YGK',
    power: 28,
    rareBonus: 5,
    maxDurability: 140,
    price: 450,
    unlockLevel: 7,
    desc: '矶钓专用氟碳线，低延展，高灵敏度。',
  },
  {
    id: 'line_005',
    name: '达亿瓦ASTRON 4.0号',
    type: 'line',
    brand: '达亿瓦',
    power: 35,
    rareBonus: 7,
    maxDurability: 160,
    price: 550,
    unlockLevel: 10,
    desc: 'DAIWA高端尼龙线，抗冲击性能优异。',
  },
  {
    id: 'line_006',
    name: 'Sunline 船钓PE 5.0号',
    type: 'line',
    brand: 'Sunline',
    power: 42,
    rareBonus: 8,
    maxDurability: 180,
    price: 700,
    unlockLevel: 14,
    desc: '船钓专用PE线，超强耐磨，深水作战首选。',
  },
  {
    id: 'line_007',
    name: '西格巨物氟碳线 6.0号',
    type: 'line',
    brand: '西格',
    power: 50,
    rareBonus: 10,
    maxDurability: 200,
    price: 900,
    unlockLevel: 18,
    desc: '极限拉力氟碳线，专为百斤级巨物设计。',
  },
]
