import type { EquipDef } from '../../types'

export const REELS: EquipDef[] = [
  {
    id: 'reel_001',
    name: '达亿瓦Crossfire 1000',
    type: 'reel',
    brand: '达亿瓦Crossfire',
    power: 10,
    rareBonus: 0,
    maxDurability: 100,
    price: 400,
    unlockLevel: 1,
    desc: '入门纺车轮，轻量机身，适合新手练习。',
  },
  {
    id: 'reel_002',
    name: '禧玛诺塞纳 2500',
    type: 'reel',
    brand: '禧玛诺塞纳',
    power: 18,
    rareBonus: 2,
    maxDurability: 120,
    price: 600,
    unlockLevel: 4,
    desc: '入门级纺车轮，静音顺滑，性价比高。',
  },
  {
    id: 'reel_003',
    name: '迪佳GTR 3000',
    type: 'reel',
    brand: '迪佳',
    power: 25,
    rareBonus: 4,
    maxDurability: 140,
    price: 900,
    unlockLevel: 7,
    desc: '中型纺车轮，金属机身，坚固耐用。',
  },
  {
    id: 'reel_004',
    name: '光威武神 4000',
    type: 'reel',
    brand: '光威',
    power: 32,
    rareBonus: 5,
    maxDurability: 160,
    price: 1200,
    unlockLevel: 9,
    desc: '大容量线杯，远投强劲，海边滩钓利器。',
  },
  {
    id: 'reel_005',
    name: '池刃铁板轮 5000',
    type: 'reel',
    brand: '池刃',
    power: 38,
    rareBonus: 7,
    maxDurability: 180,
    price: 1600,
    unlockLevel: 12,
    desc: '铁板专用轮，强力刹车系统，远投稳定。',
  },
  {
    id: 'reel_006',
    name: '禧玛诺NEXAVE 6000',
    type: 'reel',
    brand: '禧玛诺NEXAVE',
    power: 45,
    rareBonus: 8,
    maxDurability: 195,
    price: 2200,
    unlockLevel: 15,
    desc: '禧玛诺中高端轮，X-SHIP齿轮系统，收线顺畅。',
  },
  {
    id: 'reel_007',
    name: '狼王手刹轮 4000',
    type: 'reel',
    brand: '狼王手刹',
    power: 50,
    rareBonus: 9,
    maxDurability: 210,
    price: 2800,
    unlockLevel: 18,
    desc: '手刹制动设计，精准控鱼，矶钓玩家最爱。',
  },
  {
    id: 'reel_008',
    name: '达亿瓦Crossfire 8000',
    type: 'reel',
    brand: '达亿瓦Crossfire',
    power: 55,
    rareBonus: 10,
    maxDurability: 230,
    price: 3500,
    unlockLevel: 21,
    desc: '大型远投轮，高强度齿轮，深海船钓首选。',
  },
  {
    id: 'reel_009',
    name: '池刃巨物纺车 10000',
    type: 'reel',
    brand: '池刃',
    power: 60,
    rareBonus: 12,
    maxDurability: 250,
    price: 4200,
    unlockLevel: 24,
    desc: '旗舰巨物轮，全金属壳体，百斤鱼获不惧。',
  },
]
