import type { EquipDef } from '../../types'

export const RODS: EquipDef[] = [
  {
    id: 'rod_001',
    name: '汉鼎雷霆鲫鱼竿',
    type: 'rod',
    brand: '汉鼎',
    power: 10,
    rareBonus: 0,
    maxDurability: 100,
    price: 500,
    unlockLevel: 1,
    desc: '入门级鲫鱼竿，轻量韧性好，适合近岸垂钓。',
  },
  {
    id: 'rod_002',
    name: '法莱海玲珑',
    type: 'rod',
    brand: '法莱',
    power: 18,
    rareBonus: 2,
    maxDurability: 120,
    price: 800,
    unlockLevel: 3,
    desc: '海钓入门竿，玻璃钢材质，耐腐蚀性佳。',
  },
  {
    id: 'rod_003',
    name: '光威小海竿',
    type: 'rod',
    brand: '光威',
    power: 25,
    rareBonus: 3,
    maxDurability: 140,
    price: 1100,
    unlockLevel: 5,
    desc: '光威经典海竿，性价比高，抛投顺畅。',
  },
  {
    id: 'rod_004',
    name: '迪佳波浪矶',
    type: 'rod',
    brand: '迪佳',
    power: 32,
    rareBonus: 5,
    maxDurability: 160,
    price: 1500,
    unlockLevel: 7,
    desc: '矶钓专用竿，高感度竿梢，灵敏捕捉鱼讯。',
  },
  {
    id: 'rod_005',
    name: '狼王远攻矶',
    type: 'rod',
    brand: '狼王',
    power: 38,
    rareBonus: 6,
    maxDurability: 180,
    price: 1800,
    unlockLevel: 9,
    desc: '远投型矶钓竿，腰力强劲，抗风浪表现优异。',
  },
  {
    id: 'rod_006',
    name: '达亿瓦斯巴达',
    type: 'rod',
    brand: '达亿瓦',
    power: 45,
    rareBonus: 8,
    maxDurability: 200,
    price: 2200,
    unlockLevel: 11,
    desc: '高性能海竿，高碳纤维材质，轻量高硬度。',
  },
  {
    id: 'rod_007',
    name: '禧玛诺BB-X LARISSA',
    type: 'rod',
    brand: '禧玛诺',
    power: 50,
    rareBonus: 10,
    maxDurability: 210,
    price: 2600,
    unlockLevel: 13,
    desc: '禧玛诺经典矶竿，精密工艺，控鱼稳定。',
  },
  {
    id: 'rod_008',
    name: '君德激浪',
    type: 'rod',
    brand: '君德',
    power: 55,
    rareBonus: 10,
    maxDurability: 230,
    price: 3000,
    unlockLevel: 15,
    desc: '激浪系列船钓竿，大导环设计，出线顺畅。',
  },
  {
    id: 'rod_009',
    name: '法莱海上霸王',
    type: 'rod',
    brand: '法莱',
    power: 60,
    rareBonus: 12,
    maxDurability: 250,
    price: 3400,
    unlockLevel: 17,
    desc: '大型海钓竿，超强拉力，专攻巨物。',
  },
  {
    id: 'rod_010',
    name: '光威大矶王',
    type: 'rod',
    brand: '光威',
    power: 65,
    rareBonus: 12,
    maxDurability: 260,
    price: 3800,
    unlockLevel: 19,
    desc: '大矶王系列，加厚竿壁，暴力起鱼不惧。',
  },
  {
    id: 'rod_011',
    name: '伽玛卡兹金刚',
    type: 'rod',
    brand: '伽玛卡兹',
    power: 70,
    rareBonus: 13,
    maxDurability: 275,
    price: 4200,
    unlockLevel: 21,
    desc: '日本原厂工艺，超强韧性，深海利器。',
  },
  {
    id: 'rod_012',
    name: '达亿瓦极限海魂',
    type: 'rod',
    brand: '达亿瓦',
    power: 75,
    rareBonus: 14,
    maxDurability: 290,
    price: 4600,
    unlockLevel: 23,
    desc: '旗舰级海钓竿，四轴碳布卷制，极致手感。',
  },
  {
    id: 'rod_013',
    name: '禧玛诺Twinpower深海',
    type: 'rod',
    brand: '禧玛诺',
    power: 80,
    rareBonus: 15,
    maxDurability: 300,
    price: 5000,
    unlockLevel: 25,
    desc: '专业深海船钓竿，顶级配置，无惧深海巨兽。',
  },
]
